### ISSUE TITLE
Thaumcraft Compatability

### ISSUE THREAD

**Issue by dexman545** [vidaj/TFCWaterCompatibility#1]
Thank you for making this mod, it has been a great help :).

I was wondering if you could allows TFC fresh water to be placed in Thaumcraft's crucible. Currently, this is not possible, and has been a great hindrance in developing modpacks.

**Comment by vidaj** [comment]
Hi! 

I can take a look how thaumcraft handles liquids in the crucible. I would guess that Azanor would be the one to fix it, but I can help figuring out what to fix :) If there's anything I can do on my end, I will include it in the mod.

**Comment by vidaj** [comment]
Yeah, adding dependency to Thaumcraft fixed the issue with crucibles. Uploading new version 1.1 to curseforge now :)

**Comment by dexman545** [comment]
Thank you very much :)
