### ISSUE TITLE
Error within fluid registery

### ISSUE THREAD

**Issue by dexman545** [vidaj/TFCWaterCompatibility#6]
Using this mod with Forge 10.13.4.1448 and the most recent TFC throws this error when creating a new single player world: http://paste.ee/p/SpkTR Most relevant stuff begins at line 170

**Comment by vidaj** [comment]
Weird. Which version of tfcwatercompatibility are you using?

**Comment by dexman545** [comment]
I was using version 1.3

**Comment by dexman545** [comment]
just sent a pull request that fixes this. I updated Forge, the TFC API, and added TFC deobfuscated to the libs folder, that seems to have fixed the bug. 

-kev12east
